Updates for the Taquito-based NFT tutorial
trilitech/tezos-developer-docs pull request #115
Opened 2023-09-20 20:27 UTC by timothymcmackin

Depends on https://github.com/trilitech/tezos-developer-docs/pull/114.

Preview: https://docs-staging-git-feat-nft-taquito-tutorial-trili-tech.vercel.app/tutorials/create-an-nft/nft-taquito/

This is an update of the tutorial that creates a web app that mints NFTs. I've tried to simplify it and make the steps easier to follow.

TODOs:
- [x] Before merging this tutorial, make the trilitech/tutorial-applications repo public.
- [x] Come up with a way to make the diagram image expand so people can read it -- this may be able to wait till we're on a new platform -- I have this working in the new platform
- [X] Instructions for funding the user's wallet

Questions:
- Is there a way to get the contract address later if I forget to copy it when I originate via the LIGO IDE?
- I changed the counter tutorial from a main function to individual entrypoint functions because main() was deprecated. Should I do that here?
- I removed the following details as too technical for the context; is that OK?

> The id is returned by Taquito as a `BigNumber`, so you have to call `.toNumber()` first before being able to use it. Once we have the id, we can look for its metadata in the `token_metadata` bigmap. The value returned is a Michelson map and the metadata path is going to be stored at the empty key. Because the path is stored as bytes, we use `bytes2Char()` provided by the `@taquito/utils` package to convert the returned `bytes` into a `string`. To finish, we return an object with 2 properties: the token id and the IPFS hash of the metadata.

> Note: although the standard requires us to store the IPFS hash in the following manner =&gt; `ipfs://IPFS_HASH`, there is no safeguard and any kind of data can be stored there, this is why we make a simple check with `tokenInfo.slice(0, 7) === “ipfs://”` using the ternary operator to verify that at least this condition is fulfilled.

> The `bind` attribute in Svelte makes it very easy to store the input in a variable that we can use later when we want to pin the NFT to the IPFS. A click on the `upload` button will trigger the upload of the picture, its title, and description to the server.

> We define 2 boolean variables called `pinningMetadata` and `mintingToken` that we will update according to the result of the different steps of the upload to give some visual feedback to the users in the UI.

2023-09-22 10:12 UTC, claudebarde commented on src/pages/tutorials/create-an-nft/nft-taquito/index.md
> +- How to deploy (originate) a smart contract to Tezos
"Originate" is the official lingo on Tezos, so it should rather be `How to originate (deploy) a smart contract to Tezos`

2023-09-22 10:16 UTC, claudebarde commented on src/pages/tutorials/create-an-nft/nft-taquito/index.md
> +In this case, it accepts the entrypoint that the client called and the current state of the contract's storage.
The "client" on Tezos is called the `sender`

2023-09-22 10:23 UTC, claudebarde commented on src/pages/tutorials/create-an-nft/nft-taquito/index.md
> +   The `reverse_ledger` variable in the contract storage keeps a list of who owns each NFT.
I am not sure the word `variable` is appropriate here. These names are rather `properties` of the storage, `variable` may make it look like they can change, but they don't.

2023-09-22 10:24 UTC, claudebarde commented on src/pages/tutorials/create-an-nft/nft-taquito/index.md
> +For example, you could add entrypoints
It looks like something is missing here or the line should be removed altogether.

2023-09-22 10:36 UTC, claudebarde commented on src/pages/tutorials/create-an-nft/nft-tznft/index.md
> +- How to deploy (or _mint_) the NFTs to the sandbox
`mint` is the correct term, `deploy` is only used for smart contracts.

2023-09-22 10:40 UTC, claudebarde commented on src/pages/tutorials/create-an-nft/nft-tznft/index.md
> +   Unlike the live Tezos networks, this sandbox bakes a new block every 5 seconds.
Not sure if that's relevant and is worth adding, but the 5-second block time is by default, it is possible to change that parameter when launching Flextesa.

2023-09-22 10:44 UTC, claudebarde commented on src/pages/tutorials/create-an-nft/nft-tznft/index.md
> +IPFS requires authentication just like blockchain transactions, so in this section you set up an account with the Pinata IPFS provider and use it to upload (or _pin_) the NFT data to IPFS.
The IPFS doesn't require authentication, everybody can run a node and send files to the network. Only Pinata requires authentication in order to "pin" the files and persist them on the network because files that are not used and not pinned on the IPFS are automatically deleted after a certain period of time.

2023-09-22 10:48 UTC, claudebarde requested changes
Please check the comments I left, thank you!

2023-09-22 13:15 UTC, timothymcmackin commented
@claudebarde Made updates; thanks for the corrections!

2023-09-22 15:01 UTC, claudebarde submitted a review, later dismissed

2023-10-11 12:35 UTC, claudebarde commented on src/pages/tutorials/create-an-nft/nft-taquito/index.md
> +   1. Click **Deploy** and leave the window open to wait for the contract to be originate.
Little typo here: "originated"

2023-10-13 10:33 UTC, beatalipska approved these changes
🚀 for me - wow!

2023-10-13 12:35 UTC, merged