Topic on calling contracts from dApps
trilitech/tezos-developer-docs pull request #139
Opened 2023-10-31 19:19 UTC by timothymcmackin

2023-11-13 11:56 UTC, claudebarde commented on docs/dApps/sending-transactions.md
> +A call to a smart contract always includes a transfer of a certain amount of tez, even if that amount is zero.
Could you explain what you mean here? I believe a transaction with 0 tez is a transaction that didn't transfer any tez.

2023-11-13 11:59 UTC, claudebarde commented on docs/dApps/sending-transactions.md
> +To send tez with Taquito, connect to the user's wallet and use the `Tezos.wallet.transfer` method, as in this example:
I think it would be worth mentioning that you can also use the Contract API to send tez, in addition to the Wallet API.

2023-11-13 12:05 UTC, claudebarde commented on docs/dApps/sending-transactions.md
> +IDEs may warn that the method does not exist because they are not aware of the entrypoints on the contract.
I generally get an error message in VSCode when I try to call a method that doesn't exist on an object in TypeScript, VSCode at least is aware of the entrypoint methods, I don't know about the other IDEs.

2023-11-13 14:54 UTC, timothymcmackin commented on docs/dApps/sending-transactions.md
> +IDEs may warn that the method does not exist because they are not aware of the entrypoints on the contract.
I see an error in VScode when I try to call a contract entrypoint through the wallet API. How would VScode know what entrypoints are available on a contract?
<img width="608" alt="Screenshot 2023-11-13 at 9 54 31 AM" src="https://github.com/trilitech/tezos-developer-docs/assets/6494785/78b95220-c3b7-48c1-904f-aaba7ec27f2f">

2023-11-13 15:03 UTC, timothymcmackin commented on docs/dApps/sending-transactions.md
> +A call to a smart contract always includes a transfer of a certain amount of tez, even if that amount is zero.
This last sentence should probably be a separate note. I'll move it. I think it's clear: when you call a smart contract entrypoint you always transfer some amount of tez , even if that amount is zero.

2023-11-13 15:21 UTC, timothymcmackin commented on docs/dApps/sending-transactions.md
> +A call to a smart contract always includes a transfer of a certain amount of tez, even if that amount is zero.
@claudebarde I rewrote the intro section to clarify this note -- let me know what you think.

2023-11-13 15:22 UTC, timothymcmackin commented on docs/dApps/sending-transactions.md
> +To send tez with Taquito, connect to the user's wallet and use the `Tezos.wallet.transfer` method, as in this example:
"You can also use the Taquito Contract API to send tez in a similar way."

2023-11-13 15:46 UTC, claudebarde commented on docs/dApps/sending-transactions.md
> +IDEs may warn that the method does not exist because they are not aware of the entrypoints on the contract.
You provided the wrong example, `get` is a method on a big map abstraction, not an entrypoint.
I may be wrong as I haven't used it in a while, but I can't remember VSCode complaining about a method on `Tezos.contract.methods`. Did you experience that?

2023-11-13 16:53 UTC, timothymcmackin commented on docs/dApps/sending-transactions.md
> +IDEs may warn that the method does not exist because they are not aware of the entrypoints on the contract.
No, in this case, the contract has an entrypoint named "get".

2023-11-13 16:57 UTC, timothymcmackin commented on docs/dApps/sending-transactions.md
> +IDEs may warn that the method does not exist because they are not aware of the entrypoints on the contract.
Oh, I see -- VScode is not showing errors on Tezos.contract.methods. I'll remove this note from the docs.

2023-11-16 14:01 UTC, claudebarde commented on docs/dApps/sending-transactions.md
> +await contract.methods.doSomething('Param 1', 25)
If you are using `.then`, you don't need `await`. Using `await` is preferable though, in my opinion.
```
try {
    let op = await contract.methods.doSomething('Param 1', 25).send();
    console.log(`Waiting for ${op.opHash} to be confirmed...`);
    await op.confirmation(2);
} catch (error) {
    console.log(`Error: ${JSON.stringify(error, null, 2)}`)
}
```

2023-11-16 14:02 UTC, claudebarde requested changes
See comment on line 76

2023-11-16 14:44 UTC, merged