Use the online IDE for the smartpy tutorial
trilitech/tezos-developer-docs pull request #159
Opened 2023-11-09 21:01 UTC by timothymcmackin

This version of the first smart contract tutorial uses the smartpy online IDE instead of the octez client. It may be a bit easier to follow if the reader isn't comfortable with the command line or can't install things locally, but the smartpy IDE interface is pretty complicated, so I'm not sure which version is better.

2023-11-20 11:12 UTC, onedebos commented
Reviewed. Looks simple enough to follow along using the IDE.

2023-11-24 14:31 UTC, claudebarde commented on docs/tutorials/smart-contract/smartpy.md
> +- It has one or more entrypoints, which are a kind of function that clients can call, like endpoints in an API or functions or methods in many programming languages
It is more accurate to say that a smart contract has code that can be executed instead of entrypoints. Maybe it can be added that the code is executed by calling one of the entrypoints, but some contracts don't have entrypoints (the "default" entrypoint is just a shortcut to make it easier to understand how it works, but there is technically no entrypoint)

2023-11-24 14:32 UTC, claudebarde commented on docs/tutorials/smart-contract/smartpy.md
> +- It has a Tezos account and can store tez
The contract is an account itself, a programmable account through its Michelson code, it doesn't have an account.

2023-11-24 14:38 UTC, claudebarde requested changes
Please see comments

2023-11-27 21:10 UTC, timothymcmackin commented on docs/tutorials/smart-contract/smartpy.md
> +- It has one or more entrypoints, which are a kind of function that clients can call, like endpoints in an API or functions or methods in many programming languages
I think for this "first smart contract" tutorial, describing the contract as having entrypoints is the clear way to do it. We should work out the explanation of the default entrypoint here:
https://github.com/trilitech/tezos-developer-docs/blob/staging/docs/smart-contracts/entrypoints.md?plain=1#L47

2023-11-27 21:13 UTC, timothymcmackin commented on docs/tutorials/smart-contract/smartpy.md
> +- It has a Tezos account and can store tez
> It has a Tezos account and can store tez (technically, the contract is itself a type of Tezos account, but you can think of it as a program with a Tezos account)

2023-12-05 15:12 UTC, merged