Tutorial dapp
trilitech/tezos-developer-docs pull request #197
Opened 2023-12-01 15:55 UTC by zamrokk

Add the 4 dapp tutorials of the Marigold learning page

2023-12-01 16:43 UTC, onedebos approved these changes

2023-12-01 17:10 UTC, timothymcmackin requested changes
The build is failing because the `title` field of the markdown files is not valid. Use quotes for the strings because  they contain colons.

2023-12-01 17:10 UTC, timothymcmackin commented on docs/tutorials/dapp/part-1.md
> +title: Part 1 : Create your minimum dapp on Tezos
```suggestion
title: "Part 1: Create your minimum dapp on Tezos"
```

2023-12-01 17:10 UTC, timothymcmackin commented on docs/tutorials/dapp/part-2.md
> +title: Part 2: Inter-contract calls and testing
```suggestion
title: "Part 2: Inter-contract calls and testing"
```

2023-12-01 17:10 UTC, timothymcmackin commented on docs/tutorials/dapp/part-3.md
> +title: Part 3: Tickets
```suggestion
title: "Part 3: Tickets"
```

2023-12-01 17:10 UTC, timothymcmackin commented on docs/tutorials/dapp/part-4.md
> +title: Part 4: Smart contract upgrades
```suggestion
title: "Part 4: Smart contract upgrades"
```

2023-12-01 18:10 UTC, timothymcmackin requested changes
Also need to remove the "th" from the dates to make Docusaurus handle them correctly.

2023-12-01 18:10 UTC, timothymcmackin commented on docs/tutorials/dapp/part-1.md
> +  date: 27th November 2023
```suggestion
  date: 27 November 2023
```

2023-12-01 18:10 UTC, timothymcmackin commented on docs/tutorials/dapp/part-2.md
> +  date: 28th November 2023
```suggestion
  date: 28 November 2023
```

2023-12-01 18:10 UTC, timothymcmackin commented on docs/tutorials/dapp/part-3.md
> +  date: 29th November 2023
```suggestion
  date: 29 November 2023
```

2023-12-01 18:12 UTC, timothymcmackin commented on docs/tutorials.mdx
> +import TutorialCardContainer from "@site/src/components/TutorialCardContainer";
```suggestion
import TutorialCardContainer from "@site/src/components/TutorialCardContainer";
```

2023-12-01 18:15 UTC, timothymcmackin commented on docs/tutorials/dapp.md
> +![](/img/tutorials/dapp-table.png)
```suggestion
![Example of the table of addresses and which addresses poked them](/img/tutorials/dapp-table.png)
```

2023-12-01 18:16 UTC, timothymcmackin commented on docs/tutorials/dapp/part-1.md
> +![](./img/tutorials/dapp-logged.png)
```suggestion
![The app after you have connected, showing your address and tex balance](/img/tutorials/dapp-logged.png)
```

2023-12-01 18:18 UTC, timothymcmackin commented on docs/tutorials/dapp/part-2.md
> +![result](./img/tutorials/dapp-result.png)
```suggestion
![The dApp page showing the result of the poke action](/img/tutorials/dapp-result.png)
```

2023-12-01 18:18 UTC, timothymcmackin commented on docs/tutorials/dapp/part-3.md
> +![pokefail](./img/tutorials/dapp-pokefail.png)
```suggestion
![pokefail](/img/tutorials/dapp-pokefail.png)
```

2023-12-01 18:18 UTC, timothymcmackin commented on docs/tutorials/dapp/part-3.md
> +![kukaifail](./img/tutorials/dapp-kukaifail.png)
```suggestion
![kukaifail](/img/tutorials/dapp-kukaifail.png)
```

2023-12-01 18:19 UTC, timothymcmackin commented on docs/tutorials/dapp/part-3.md
> +![mint](./img/tutorials/dapp-mint.png)
```suggestion
![mint](/img/tutorials/dapp-mint.png)
```

2023-12-01 18:19 UTC, timothymcmackin commented on docs/tutorials/dapp/part-3.md
> +![success](./img/tutorials/dapp-success.png)
```suggestion
![success](/img/tutorials/dapp-success.png)
```

2023-12-01 18:19 UTC, timothymcmackin commented on docs/tutorials/dapp/part-3.md
> +![kukaifail](./img/tutorials/dapp-kukaifail.png)
```suggestion
![kukaifail](/img/tutorials/dapp-kukaifail.png)
```

2023-12-01 18:45 UTC, timothymcmackin commented
- For accessibility, provide alt text for images within the link brackets `![alt text](/img/path/image.png)`
- Add the tutorial to the `tutorialsSidebar` in `sidebars.js`
- Settle on capitalization for "dapp." I've been using "dApp."
- We can add the completed application to https://github.com/trilitech/tutorial-applications with the others.
- Instead of naming the folder `training`, how about `pokeGame` or something that won't conflict with the other "training" tutorials?
- For links, consider linking to docs.tezos.com where possible instead of sending people elsewhere. In part 1, there are links that could go to https://docs.tezos.com/smart-contracts/entrypoints and https://docs.tezos.com/smart-contracts/data-types/complex-data-types#variants.
- To make the tutorial easy to follow, I like to make everything that the user does a numbered step. The section in part 1 under "write the poke function" has a lot of things that the user does that aren't steps, so it might get confusing. That's just how I've been trying to do the other tutorials.
- Consistency: Start bulleted lists with a capital letter and end sentences with a period.
- Indents: it would be easier to follow if the contents of a numbered step were indented so the things that were part of the step were farther to the right than the number. (see attached screencap)
- Don't include a space before a colon.
- I will enable mermaid diagrams for you; the diagrams do not appear properly.
- This is a long enough tutorial that it should be in the intermediate section in `tutorials.mdx`.

![Screenshot 2023-12-01 at 1 37 33 PM](https://github.com/trilitech/tezos-developer-docs/assets/6494785/e243056c-8ea7-4f89-934e-6005a084202a)

2023-12-04 20:41 UTC, timothymcmackin commented on docs/tutorials.mdx
> +import TutorialCardContainer from "@site/src/components/TutorialCardContainer";
The build is failing because of this duplicate import.

2023-12-06 09:26 UTC, zamrokk commented
> * For accessibility, provide alt text for images within the link brackets `![alt text](/img/path/image.png)`
> 
>     * Add the tutorial to the `tutorialsSidebar` in `sidebars.js`
> 
>     * Settle on capitalization for "dapp." I've been using "dApp."
> 
>     * We can add the completed application to https://github.com/trilitech/tutorial-applications with the others.
> 
>     * Instead of naming the folder `training`, how about `pokeGame` or something that won't conflict with the other "training" tutorials?
> 
>     * For links, consider linking to docs.tezos.com where possible instead of sending people elsewhere. In part 1, there are links that could go to https://docs.tezos.com/smart-contracts/entrypoints and https://docs.tezos.com/smart-contracts/data-types/complex-data-types#variants.
> 
>     * To make the tutorial easy to follow, I like to make everything that the user does a numbered step. The section in part 1 under "write the poke function" has a lot of things that the user does that aren't steps, so it might get confusing. That's just how I've been trying to do the other tutorials.
> 
>     * Consistency: Start bulleted lists with a capital letter and end sentences with a period.
> 
>     * Indents: it would be easier to follow if the contents of a numbered step were indented so the things that were part of the step were farther to the right than the number. (see attached screencap)
> 
>     * Don't include a space before a colon.
> 
>     * I will enable mermaid diagrams for you; the diagrams do not appear properly.
> 
>     * This is a long enough tutorial that it should be in the intermediate section in `tutorials.mdx`.
> 
> 
> ![Screenshot 2023-12-01 at 1 37 33 PM](https://private-user-images.githubusercontent.com/6494785/287354568-e243056c-8ea7-4f89-934e-6005a084202a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2ODU3MDUsIm5iZiI6MTcwMTY4NTQwNSwicGF0aCI6Ii82NDk0Nzg1LzI4NzM1NDU2OC1lMjQzMDU2Yy04ZWE3LTRmODktOTM0ZS02MDA1YTA4NDIwMmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDRUMTAyMzI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzY5ZDQ0YzVhNWJkMTU0YzNmZmVlZTBlNjZmYjJiMGIwMzgyZGZmYjdlNjEzODY5NGM1ODI0ZWE2YjRhMjE3OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.vYhrN_F_T5o3tFNKQqIljoTt2FUJ0BhlVpOr5Ykqn2M)

Very valuable comments. Thank you Tim

2023-12-06 09:31 UTC, zamrokk commented
I cannot access Vercel to see what failed 
Can someone help me on this ?

2023-12-06 13:42 UTC, zamrokk commented
> > I cannot access Vercel to see what failed Can someone help me on this ?
> 
> @zamrokk The problem is the duplicate import here: https://github.com/trilitech/tezos-developer-docs/pull/197/files#diff-03cbcc9e6b2a55c9cf2d73092d78ddc7fa68f4d3d90d1f79b8d0707a1d1633b4R8-R9

oh wahou ! When I save and VsCode autoformats the file, then it is duplicating the line o.O
What a weird bug

2023-12-06 13:51 UTC, zamrokk commented
> > > I cannot access Vercel to see what failed Can someone help me on this ?
> > 
> > 
> > @zamrokk The problem is the duplicate import here: https://github.com/trilitech/tezos-developer-docs/pull/197/files#diff-03cbcc9e6b2a55c9cf2d73092d78ddc7fa68f4d3d90d1f79b8d0707a1d1633b4R8-R9
> 
> oh wahou ! When I save and VsCode autoformats the file, then it is duplicating the line o.O What a weird bug

bug open : https://github.com/mdx-js/mdx/issues/2412

2023-12-08 08:57 UTC, zamrokk commented on docs/tutorials/dapp/part-1.md
> +1. Try to poke. The Ligo command-line provides sub-commands to test your Ligo code
true, it was the tittle of a subsection that disappeared with numbering. I am fixing this .. thx

2023-12-08 13:35 UTC, zamrokk commented on docs/tutorials/dapp/part-1.md
> +   - **return\_**: a pair of list of `operation` and a storage. This is mandatory by convention. You can only define another variable name, that is not a keyword, if you want.
- I will reformulate then
- I will explain unit
- I keep it the simplest as possible just to start
- yes variable naming is free, just return type is fixed

2023-12-08 13:48 UTC, zamrokk commented on sidebars.js
> -      type: 'category',
It is babel parser that does it for the js file .. I will try to remove it

2023-12-08 13:55 UTC, zamrokk commented on sidebars.js
> -      type: 'category',
Well, I read some docs and it is more recommended to have double quotes than single quotes

-     Newcomers will already be familiar with double quotes from their language. In English, we must use double quotes " to identify a passage of quoted text. 
-     Double quotes eliminate the need to escape apostrophes 
-     Double quotes mean a string in many other languages.
-     JSON notation is written with double quotes.

2023-12-08 14:32 UTC, zamrokk commented on docs/tutorials/dapp/part-1.md
> +1. Configure your wallet to get free Tez.
there are 2 choices : use alice account or put money on the generated account

2023-12-08 15:24 UTC, timothymcmackin approved these changes

2023-12-08 15:27 UTC, merged